# Generated by Django 4.0.4 on 2022-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_billing',
            field=models.BooleanField(default=False, verbose_name='Do you want to set as default billing address?'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_shipping',
            field=models.BooleanField(default=False, verbose_name='Do you want to set as default shipping address?'),
        ),
    ]
