# Generated by Django 4.0.4 on 2022-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootuser',
            name='address',
            field=models.ManyToManyField(to='administration.shippingaddress'),
        ),
    ]
