# Generated by Django 4.0.4 on 2022-04-17 12:35

from django.db import migrations, models
import product_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=product_management.models.image_directory_path),
        ),
    ]
