# Generated by Django 4.0.4 on 2022-04-18 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0002_product_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('display_status', models.IntegerField(choices=[(None, 'SELECT'), (0, 'PUBLISH'), (1, 'DRAFT')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart_id', models.CharField(max_length=100, null=True, verbose_name='Order ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('tax', models.DecimalField(decimal_places=2, default=18.0, max_digits=10, null=True, verbose_name='Discount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Payable')),
                ('payment_status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'PAID')], default=0, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('display_status', models.IntegerField(choices=[(None, 'SELECT'), (0, 'PUBLISH'), (1, 'DRAFT')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_category', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(null=True, verbose_name='Purchased Quantity')),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
